name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "BrewerHerokuTutorial" #Must be unique in Heroku
          heroku_email: "brianobrunoswe@gmail.com"
          dontuseforce: 1
          docker_heroku_process_type: "web" #OPTIONAL and DEFAULT - "web"
